import js from "@eslint/js";

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        // Node.js globals
        console: "readonly",
        process: "readonly",
        Buffer: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        fetch: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        crypto: "readonly",
        btoa: "readonly",
        atob: "readonly",
        globalThis: "readonly",
        structuredClone: "readonly",
        // CJS compatibility (project mixes ESM and CJS)
        require: "readonly",
        module: "readonly",
        exports: "readonly",
        global: "readonly",
        define: "readonly",
      },
    },
    rules: {
      // Errors
      "no-undef": "warn",
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-constant-condition": "warn",
      "no-debugger": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-empty": ["warn", { allowEmptyCatch: true }],
      "no-extra-semi": "warn",
      "no-redeclare": "warn",
      "no-prototype-builtins": "warn",
      "no-unreachable": "error",
      "no-unsafe-finally": "error",

      // Best practices
      "eqeqeq": ["warn", "always", { null: "ignore" }],
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-new-func": "error",
      "no-throw-literal": "warn",
      "no-self-compare": "warn",
      "no-self-assign": "warn",
      "no-cond-assign": "warn",
      "no-template-curly-in-string": "warn",

      // Style (minimal)
      "no-mixed-spaces-and-tabs": "warn",
      "no-trailing-spaces": "off",
      "semi": "off",
    },
  },
  {
    // Test files
    files: ["tests/**/*.js", "**/*.test.js"],
    languageOptions: {
      globals: {
        describe: "readonly",
        it: "readonly",
        test: "readonly",
        expect: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        jest: "readonly",
      },
    },
  },
  {
    // Client SDK — mixed browser/node environment
    files: ["client/**/*.js"],
    languageOptions: {
      globals: {
        window: "readonly",
        document: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        navigator: "readonly",
        location: "readonly",
        CustomEvent: "readonly",
        Event: "readonly",
        AbortController: "readonly",
        FormData: "readonly",
        require: "readonly",
        module: "readonly",
        exports: "readonly",
      },
    },
  },
  {
    // Browser scripts (webapp)
    files: ["webapp/**/*.js"],
    languageOptions: {
      globals: {
        window: "readonly",
        document: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        navigator: "readonly",
        location: "readonly",
        history: "readonly",
        HTMLElement: "readonly",
        CustomEvent: "readonly",
        Event: "readonly",
        alert: "readonly",
        confirm: "readonly",
        FormData: "readonly",
        Headers: "readonly",
        Request: "readonly",
        Response: "readonly",
        AbortController: "readonly",
        MutationObserver: "readonly",
        IntersectionObserver: "readonly",
        WebSocket: "readonly",
        AbortSignal: "readonly",
        File: "readonly",
        self: "readonly",
        msCrypto: "readonly",
        prompt: "readonly",
      },
    },
  },
  {
    ignores: [
      "node_modules/",
      "contracts/lib/",
      "contracts/out/",
      "contracts/cache/",
      "wasm-core/pkg/",
      "wasm-core/target/",
      "webapp/public/wasm/",
      "dist/",
      "webapp/public/js/rwa-credential-mint.js",
      "*.config.js",
      "*.config.cjs",
      "babel.config.cjs",
    ],
  },
];
