#!/usr/bin/env node
/**
 * generate-env.mjs — Generate environment config from profile JSON
 *
 * Usage: node scripts/generate-env.mjs [development|test|production]
 *
 * Reads env/<profile>.json and generates:
 *   1. env/.env.<profile>     — dotenv format for server (non-sensitive defaults)
 *   2. env/frontend.js        — ENV object for portals (authority-dashboard, client-portal, ops-portal)
 *
 * Sensitive values (ADMIN_TOKEN, YAULT_API_KEY, EMAIL_API_KEY, ARWEAVE_WALLET_JWK, etc.)
 * are NOT in JSON — set them in .env and load via dotenv.
 *
 * To add a new config field:
 *   1. Add to env/development.json, test.json, production.json
 *   2. Add to _toEnvVars() and _toFrontendJs() below
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const profile = process.argv[2] || 'development';
const validProfiles = ['development', 'test', 'production'];
if (!validProfiles.includes(profile)) {
  console.error(`[env] Invalid profile: "${profile}". Must be one of: ${validProfiles.join(', ')}`);
  process.exit(1);
}

const envPath = join(root, 'env', `${profile}.json`);
const env = JSON.parse(readFileSync(envPath, 'utf-8'));

// ---------------------------------------------------------------------------
// 1. Generate env/.env.<profile> (dotenv format for server)
// ---------------------------------------------------------------------------

function toEnvVars(cfg) {
  const lines = [
    `# Auto-generated from env/${profile}.json — DO NOT EDIT`,
    `# Generated: ${new Date().toISOString()}`,
    `# Sensitive values (ADMIN_TOKEN, YAULT_API_KEY, etc.) go in .env`,
    '',
    `ENV_PROFILE=${profile}`,
    `NODE_ENV=${cfg.server?.nodeEnv || 'development'}`,
    `PORT=${cfg.server?.port || 3001}`,
    `CORS_ORIGIN=${cfg.server?.corsOrigin ?? '*'}`,
    `DATABASE_PATH=${cfg.server?.databasePath || './data/yault.db'}`,
    '',
    `DRAND_CHAIN_HASH=${cfg.drand?.chainHash || ''}`,
    `ARWEAVE_GATEWAY=${cfg.arweave?.gateway || 'https://arweave.net'}`,
    '',
    `EMAIL_PROVIDER=${cfg.email?.provider || 'console'}`,
    `EMAIL_FROM=${cfg.email?.from || 'noreply@yault.xyz'}`,
    `TRIAL_REQUEST_EMAIL=${cfg.email?.trialRequestEmail || ''}`,
    '',
    `VAULT_RESERVE_RATIO_BPS=${cfg.vault?.reserveRatioBps ?? 2000}`,
    `SCHEDULER_POLL_MS=${cfg.scheduler?.pollIntervalMs ?? 60000}`,
    `ENABLE_TLOCK_MONITOR=${cfg.scheduler?.enableTlockMonitor ?? false}`,
    '',
    `INSURANCE_ENABLED=${cfg.insurance?.enabled !== false}`,
    `NEXUS_MUTUAL_API_URL=${cfg.insurance?.nexusMutualApi || ''}`,
    `OPENCOVER_API_URL=${cfg.insurance?.opencoverApi || ''}`,
    '',
    `EVM_RPC_URL=${cfg.claim?.evmRpcUrl || ''}`,
    `VAULT_ADDRESS=${cfg.claim?.vaultAddress || ''}`,
    '',
    `ADMIN_WALLETS=${cfg.auth?.adminWallets || ''}`,
  ];

  // RPC overrides (optional)
  const rpc = cfg.chains?.rpc || {};
  if (rpc.ethereum) lines.push(`RPC_ETHEREUM=${rpc.ethereum}`);
  if (rpc.arbitrum) lines.push(`RPC_ARBITRUM=${rpc.arbitrum}`);
  if (rpc.optimism) lines.push(`RPC_OPTIMISM=${rpc.optimism}`);
  if (rpc.base) lines.push(`RPC_BASE=${rpc.base}`);
  if (rpc.polygon) lines.push(`RPC_POLYGON=${rpc.polygon}`);
  if (rpc.bsc) lines.push(`RPC_BSC=${rpc.bsc}`);
  if (rpc.avalanche) lines.push(`RPC_AVALANCHE=${rpc.avalanche}`);
  if (rpc.solana) lines.push(`RPC_SOLANA=${rpc.solana}`);
  if (cfg.chains?.mempoolApi) lines.push(`MEMPOOL_API=${cfg.chains.mempoolApi}`);

  return lines.join('\n');
}

const envDir = join(root, 'env');
mkdirSync(envDir, { recursive: true });
const envOutPath = join(envDir, `.env.${profile}`);
writeFileSync(envOutPath, toEnvVars(env));
console.log(`[env] Wrote ${envOutPath}`);

// ---------------------------------------------------------------------------
// 2. Generate env/frontend.js (for portals)
// ---------------------------------------------------------------------------

// Sanitize string for template output (prevent injection)
const safe = (v, d = '') => {
  const s = String(v ?? d);
  return s.replace(/[`$\\]/g, (c) => (c === '`' ? '\\`' : c === '$' ? '\\$' : '\\\\'));
};

const frontendJs = `// frontend.js — AUTO-GENERATED by scripts/generate-env.mjs
// Profile: ${profile}
// Generated: ${new Date().toISOString()}
//
// DO NOT EDIT THIS FILE MANUALLY.
// Edit env/${profile}.json, then run: node scripts/generate-env.mjs ${profile}
//
// Used by: authority-dashboard, client-portal, ops-portal
// Load in HTML: <script src="env.js"></script>
// Access: window.YAULT_ENV or (typeof ENV !== 'undefined' ? ENV : {})

(function (global) {
  'use strict';
  var ENV = {
    profile: '${safe(env.profile, 'development')}',
    api: {
      baseUrl: '${safe(env.api?.baseUrl, 'http://localhost:3001/api')}',
      publicUrl: '${safe(env.api?.publicUrl, 'https://api.yault.xyz/api')}'
    },
    arweave: {
      gateway: '${safe(env.arweave?.gateway, 'https://arweave.net')}',
      graphqlEndpoint: '${safe(env.arweave?.graphqlEndpoint, 'https://arweave.net/graphql')}'
    },
    chains: {
      useTestnet: ${env.chains?.useTestnet ?? true},
      vault: ${JSON.stringify(env.chains?.vault || {})}
    },
    security: {
      // #13 FIX: Force-disable allowLocalhost and devOrigins in production profile
      allowLocalhost: ${profile === 'production' ? false : (env.security?.allowLocalhost ?? true)},
      devOrigins: ${profile === 'production' ? '[]' : JSON.stringify(env.security?.devOrigins || [])}
    },
    logging: {
      enableConsoleLog: ${env.logging?.enableConsoleLog ?? true}
    },
    rwa: {
      dev: ${profile !== 'production'},
      uploadAndMintApiUrl: ${env.rwa?.uploadAndMintApiUrl ? `'${safe(env.rwa.uploadAndMintApiUrl)}'` : 'null'},
      network: '${env.rwa?.network || (profile === 'production' ? 'mainnet' : 'devnet')}'
    }
  };
  global.YAULT_ENV = ENV;
  global.ENV = ENV;
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = ENV;
  }
})(typeof window !== 'undefined' ? window : typeof global !== 'undefined' ? global : this);
`;

const frontendPath = join(envDir, 'frontend.js');
writeFileSync(frontendPath, frontendJs);
console.log(`[env] Wrote ${frontendPath}`);

// ---------------------------------------------------------------------------
// 3. Copy frontend.js to each portal's public folder
// ---------------------------------------------------------------------------

// Copy to webapp (unified frontend) — authority-dashboard, client-portal, ops-portal removed
const webappEnvPath = join(root, 'webapp', 'public', 'js', 'env.js');
if (existsSync(join(root, 'webapp', 'public', 'js'))) {
  writeFileSync(webappEnvPath, frontendJs);
  console.log('[env] Copied to webapp/public/js/env.js');
}

console.log(`[env] Generated config for profile: ${profile}`);
